version: '3.2'
services:
  dev:
    build:
      context: ..
      dockerfile: .docker/development/Dockerfile
    volumes:
      - type: bind
        source: ../
        target: /app
      - type: bind
        source: ./development/entrypoint.js
        target: /app/entrypoint.js